#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SKELETONL3")]
	public partial class DBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAccount(Account instance);
    partial void UpdateAccount(Account instance);
    partial void DeleteAccount(Account instance);
    #endregion
		
		public DBDataContext() : 
				base(global::Model.Properties.Settings.Default.SKELETONL3ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Account> Accounts
		{
			get
			{
				return this.GetTable<Account>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.D90T0001")]
	public partial class Account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _AccountID;
		
		private string _AccountName;
		
		private string _AccountGroupID;
		
		private System.Nullable<byte> _AccountLevel;
		
		private string _DestinationAccountID;
		
		private System.Nullable<byte> _TransferLevel;
		
		private string _AccountTypeID;
		
		private string _GroupID;
		
		private byte _BaseCurrency;
		
		private bool _Balance;
		
		private bool _Disabled;
		
		private string _CreateUserID;
		
		private System.DateTime _CreateDate;
		
		private string _LastModifyUserID;
		
		private System.Nullable<System.DateTime> _LastModifyDate;
		
		private bool _OffAccount;
		
		private string _ConsoAccountID;
		
		private string _ModuleID;
		
		private byte _StyleOfTranfer;
		
		private byte _AccountStatus;
		
		private string _AccountRemark;
		
		private string _TCode01ID;
		
		private string _TCode02ID;
		
		private string _TCode03ID;
		
		private string _TCode04ID;
		
		private string _TCode05ID;
		
		private string _TCode06ID;
		
		private string _TCode07ID;
		
		private string _TCode08ID;
		
		private string _TCode09ID;
		
		private string _TCode10ID;
		
		private System.Nullable<byte> _IsMatching;
		
		private System.Nullable<byte> _IsForex;
		
		private System.Nullable<byte> _IsStockProvision;
		
		private System.Nullable<byte> _IsProgress;
		
		private string _OperatorID;
		
		private string _BankCode;
		
		private string _BankName;
		
		private string _BranchName;
		
		private string _BankAddress;
		
		private string _BankPhone;
		
		private string _BankFax;
		
		private string _BankAccountNo;
		
		private string _BankAccountName;
		
		private string _CurrencyID;
		
		private System.Nullable<System.DateTime> _OpenDate;
		
		private System.Nullable<System.DateTime> _CloseDate;
		
		private byte _PrintDetail;
		
		private byte _UseD90;
		
		private string _AccountName01;
		
		private byte _PrintOriginalInBS;
		
		private string _AccountNameU;
		
		private string _AccountName01U;
		
		private string _AccountRemarkU;
		
		private string _BankNameU;
		
		private string _BranchNameU;
		
		private string _BankAddressU;
		
		private string _BankAccountNameU;
		
		private byte _IseBanking;
		
		private string _OfficeCode;
		
		private byte _IsRevalueExchangeRate;
		
		private byte _IsAutoVATTrans;
		
		private string _DebitAccVATTrans;
		
		private string _CreditAccVATTrans;
		
		private byte _IsGroupCorAccount;
		
		private string _GainFXAccount;
		
		private string _LossFXAccount;
		
		private string _StrDivisionID;
		
		private string _StrRoleID;
		
		private string _ExcessAccount;
		
		private string _DeficiencyAccount;
		
		private string _PaymentGainFXAccount;
		
		private string _PaymentLossFXAccount;
		
		private byte _IsMatchingD03D04;
		
		private byte _IsMappingAnalysis;
		
		private string _RecVoucherTypeID;
		
		private string _PayVoucherTypeID;
		
		private string _AccountDAG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAccountIDChanging(string value);
    partial void OnAccountIDChanged();
    partial void OnAccountNameChanging(string value);
    partial void OnAccountNameChanged();
    partial void OnAccountGroupIDChanging(string value);
    partial void OnAccountGroupIDChanged();
    partial void OnAccountLevelChanging(System.Nullable<byte> value);
    partial void OnAccountLevelChanged();
    partial void OnDestinationAccountIDChanging(string value);
    partial void OnDestinationAccountIDChanged();
    partial void OnTransferLevelChanging(System.Nullable<byte> value);
    partial void OnTransferLevelChanged();
    partial void OnAccountTypeIDChanging(string value);
    partial void OnAccountTypeIDChanged();
    partial void OnGroupIDChanging(string value);
    partial void OnGroupIDChanged();
    partial void OnBaseCurrencyChanging(byte value);
    partial void OnBaseCurrencyChanged();
    partial void OnBalanceChanging(bool value);
    partial void OnBalanceChanged();
    partial void OnDisabledChanging(bool value);
    partial void OnDisabledChanged();
    partial void OnCreateUserIDChanging(string value);
    partial void OnCreateUserIDChanged();
    partial void OnCreateDateChanging(System.DateTime value);
    partial void OnCreateDateChanged();
    partial void OnLastModifyUserIDChanging(string value);
    partial void OnLastModifyUserIDChanged();
    partial void OnLastModifyDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifyDateChanged();
    partial void OnOffAccountChanging(bool value);
    partial void OnOffAccountChanged();
    partial void OnConsoAccountIDChanging(string value);
    partial void OnConsoAccountIDChanged();
    partial void OnModuleIDChanging(string value);
    partial void OnModuleIDChanged();
    partial void OnStyleOfTranferChanging(byte value);
    partial void OnStyleOfTranferChanged();
    partial void OnAccountStatusChanging(byte value);
    partial void OnAccountStatusChanged();
    partial void OnAccountRemarkChanging(string value);
    partial void OnAccountRemarkChanged();
    partial void OnTCode01IDChanging(string value);
    partial void OnTCode01IDChanged();
    partial void OnTCode02IDChanging(string value);
    partial void OnTCode02IDChanged();
    partial void OnTCode03IDChanging(string value);
    partial void OnTCode03IDChanged();
    partial void OnTCode04IDChanging(string value);
    partial void OnTCode04IDChanged();
    partial void OnTCode05IDChanging(string value);
    partial void OnTCode05IDChanged();
    partial void OnTCode06IDChanging(string value);
    partial void OnTCode06IDChanged();
    partial void OnTCode07IDChanging(string value);
    partial void OnTCode07IDChanged();
    partial void OnTCode08IDChanging(string value);
    partial void OnTCode08IDChanged();
    partial void OnTCode09IDChanging(string value);
    partial void OnTCode09IDChanged();
    partial void OnTCode10IDChanging(string value);
    partial void OnTCode10IDChanged();
    partial void OnIsMatchingChanging(System.Nullable<byte> value);
    partial void OnIsMatchingChanged();
    partial void OnIsForexChanging(System.Nullable<byte> value);
    partial void OnIsForexChanged();
    partial void OnIsStockProvisionChanging(System.Nullable<byte> value);
    partial void OnIsStockProvisionChanged();
    partial void OnIsProgressChanging(System.Nullable<byte> value);
    partial void OnIsProgressChanged();
    partial void OnOperatorIDChanging(string value);
    partial void OnOperatorIDChanged();
    partial void OnBankCodeChanging(string value);
    partial void OnBankCodeChanged();
    partial void OnBankNameChanging(string value);
    partial void OnBankNameChanged();
    partial void OnBranchNameChanging(string value);
    partial void OnBranchNameChanged();
    partial void OnBankAddressChanging(string value);
    partial void OnBankAddressChanged();
    partial void OnBankPhoneChanging(string value);
    partial void OnBankPhoneChanged();
    partial void OnBankFaxChanging(string value);
    partial void OnBankFaxChanged();
    partial void OnBankAccountNoChanging(string value);
    partial void OnBankAccountNoChanged();
    partial void OnBankAccountNameChanging(string value);
    partial void OnBankAccountNameChanged();
    partial void OnCurrencyIDChanging(string value);
    partial void OnCurrencyIDChanged();
    partial void OnOpenDateChanging(System.Nullable<System.DateTime> value);
    partial void OnOpenDateChanged();
    partial void OnCloseDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCloseDateChanged();
    partial void OnPrintDetailChanging(byte value);
    partial void OnPrintDetailChanged();
    partial void OnUseD90Changing(byte value);
    partial void OnUseD90Changed();
    partial void OnAccountName01Changing(string value);
    partial void OnAccountName01Changed();
    partial void OnPrintOriginalInBSChanging(byte value);
    partial void OnPrintOriginalInBSChanged();
    partial void OnAccountNameUChanging(string value);
    partial void OnAccountNameUChanged();
    partial void OnAccountName01UChanging(string value);
    partial void OnAccountName01UChanged();
    partial void OnAccountRemarkUChanging(string value);
    partial void OnAccountRemarkUChanged();
    partial void OnBankNameUChanging(string value);
    partial void OnBankNameUChanged();
    partial void OnBranchNameUChanging(string value);
    partial void OnBranchNameUChanged();
    partial void OnBankAddressUChanging(string value);
    partial void OnBankAddressUChanged();
    partial void OnBankAccountNameUChanging(string value);
    partial void OnBankAccountNameUChanged();
    partial void OnIseBankingChanging(byte value);
    partial void OnIseBankingChanged();
    partial void OnOfficeCodeChanging(string value);
    partial void OnOfficeCodeChanged();
    partial void OnIsRevalueExchangeRateChanging(byte value);
    partial void OnIsRevalueExchangeRateChanged();
    partial void OnIsAutoVATTransChanging(byte value);
    partial void OnIsAutoVATTransChanged();
    partial void OnDebitAccVATTransChanging(string value);
    partial void OnDebitAccVATTransChanged();
    partial void OnCreditAccVATTransChanging(string value);
    partial void OnCreditAccVATTransChanged();
    partial void OnIsGroupCorAccountChanging(byte value);
    partial void OnIsGroupCorAccountChanged();
    partial void OnGainFXAccountChanging(string value);
    partial void OnGainFXAccountChanged();
    partial void OnLossFXAccountChanging(string value);
    partial void OnLossFXAccountChanged();
    partial void OnStrDivisionIDChanging(string value);
    partial void OnStrDivisionIDChanged();
    partial void OnStrRoleIDChanging(string value);
    partial void OnStrRoleIDChanged();
    partial void OnExcessAccountChanging(string value);
    partial void OnExcessAccountChanged();
    partial void OnDeficiencyAccountChanging(string value);
    partial void OnDeficiencyAccountChanged();
    partial void OnPaymentGainFXAccountChanging(string value);
    partial void OnPaymentGainFXAccountChanged();
    partial void OnPaymentLossFXAccountChanging(string value);
    partial void OnPaymentLossFXAccountChanged();
    partial void OnIsMatchingD03D04Changing(byte value);
    partial void OnIsMatchingD03D04Changed();
    partial void OnIsMappingAnalysisChanging(byte value);
    partial void OnIsMappingAnalysisChanged();
    partial void OnRecVoucherTypeIDChanging(string value);
    partial void OnRecVoucherTypeIDChanged();
    partial void OnPayVoucherTypeIDChanging(string value);
    partial void OnPayVoucherTypeIDChanged();
    partial void OnAccountDAGChanging(string value);
    partial void OnAccountDAGChanged();
    #endregion

    public Account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string AccountID
		{
			get
			{
				return this._AccountID;
			}
			set
			{
				if ((this._AccountID != value))
				{
					this.OnAccountIDChanging(value);
					this.SendPropertyChanging();
					this._AccountID = value;
					this.SendPropertyChanged("AccountID");
					this.OnAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string AccountName
		{
			get
			{
				return this._AccountName;
			}
			set
			{
				if ((this._AccountName != value))
				{
					this.OnAccountNameChanging(value);
					this.SendPropertyChanging();
					this._AccountName = value;
					this.SendPropertyChanged("AccountName");
					this.OnAccountNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountGroupID", DbType="VarChar(20)")]
		public string AccountGroupID
		{
			get
			{
				return this._AccountGroupID;
			}
			set
			{
				if ((this._AccountGroupID != value))
				{
					this.OnAccountGroupIDChanging(value);
					this.SendPropertyChanging();
					this._AccountGroupID = value;
					this.SendPropertyChanged("AccountGroupID");
					this.OnAccountGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountLevel", DbType="TinyInt")]
		public System.Nullable<byte> AccountLevel
		{
			get
			{
				return this._AccountLevel;
			}
			set
			{
				if ((this._AccountLevel != value))
				{
					this.OnAccountLevelChanging(value);
					this.SendPropertyChanging();
					this._AccountLevel = value;
					this.SendPropertyChanged("AccountLevel");
					this.OnAccountLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DestinationAccountID", DbType="VarChar(20)")]
		public string DestinationAccountID
		{
			get
			{
				return this._DestinationAccountID;
			}
			set
			{
				if ((this._DestinationAccountID != value))
				{
					this.OnDestinationAccountIDChanging(value);
					this.SendPropertyChanging();
					this._DestinationAccountID = value;
					this.SendPropertyChanged("DestinationAccountID");
					this.OnDestinationAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransferLevel", DbType="TinyInt")]
		public System.Nullable<byte> TransferLevel
		{
			get
			{
				return this._TransferLevel;
			}
			set
			{
				if ((this._TransferLevel != value))
				{
					this.OnTransferLevelChanging(value);
					this.SendPropertyChanging();
					this._TransferLevel = value;
					this.SendPropertyChanged("TransferLevel");
					this.OnTransferLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountTypeID", DbType="VarChar(20)")]
		public string AccountTypeID
		{
			get
			{
				return this._AccountTypeID;
			}
			set
			{
				if ((this._AccountTypeID != value))
				{
					this.OnAccountTypeIDChanging(value);
					this.SendPropertyChanging();
					this._AccountTypeID = value;
					this.SendPropertyChanged("AccountTypeID");
					this.OnAccountTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupID", DbType="VarChar(20)")]
		public string GroupID
		{
			get
			{
				return this._GroupID;
			}
			set
			{
				if ((this._GroupID != value))
				{
					this.OnGroupIDChanging(value);
					this.SendPropertyChanging();
					this._GroupID = value;
					this.SendPropertyChanged("GroupID");
					this.OnGroupIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BaseCurrency", DbType="TinyInt NOT NULL")]
		public byte BaseCurrency
		{
			get
			{
				return this._BaseCurrency;
			}
			set
			{
				if ((this._BaseCurrency != value))
				{
					this.OnBaseCurrencyChanging(value);
					this.SendPropertyChanging();
					this._BaseCurrency = value;
					this.SendPropertyChanged("BaseCurrency");
					this.OnBaseCurrencyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Bit NOT NULL")]
		public bool Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this.OnBalanceChanging(value);
					this.SendPropertyChanging();
					this._Balance = value;
					this.SendPropertyChanged("Balance");
					this.OnBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Disabled", DbType="Bit NOT NULL")]
		public bool Disabled
		{
			get
			{
				return this._Disabled;
			}
			set
			{
				if ((this._Disabled != value))
				{
					this.OnDisabledChanging(value);
					this.SendPropertyChanging();
					this._Disabled = value;
					this.SendPropertyChanged("Disabled");
					this.OnDisabledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateUserID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CreateUserID
		{
			get
			{
				return this._CreateUserID;
			}
			set
			{
				if ((this._CreateUserID != value))
				{
					this.OnCreateUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreateUserID = value;
					this.SendPropertyChanged("CreateUserID");
					this.OnCreateUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreateDate", DbType="DateTime NOT NULL")]
		public System.DateTime CreateDate
		{
			get
			{
				return this._CreateDate;
			}
			set
			{
				if ((this._CreateDate != value))
				{
					this.OnCreateDateChanging(value);
					this.SendPropertyChanging();
					this._CreateDate = value;
					this.SendPropertyChanged("CreateDate");
					this.OnCreateDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifyUserID", DbType="VarChar(20)")]
		public string LastModifyUserID
		{
			get
			{
				return this._LastModifyUserID;
			}
			set
			{
				if ((this._LastModifyUserID != value))
				{
					this.OnLastModifyUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifyUserID = value;
					this.SendPropertyChanged("LastModifyUserID");
					this.OnLastModifyUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifyDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifyDate
		{
			get
			{
				return this._LastModifyDate;
			}
			set
			{
				if ((this._LastModifyDate != value))
				{
					this.OnLastModifyDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifyDate = value;
					this.SendPropertyChanged("LastModifyDate");
					this.OnLastModifyDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OffAccount", DbType="Bit NOT NULL")]
		public bool OffAccount
		{
			get
			{
				return this._OffAccount;
			}
			set
			{
				if ((this._OffAccount != value))
				{
					this.OnOffAccountChanging(value);
					this.SendPropertyChanging();
					this._OffAccount = value;
					this.SendPropertyChanged("OffAccount");
					this.OnOffAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConsoAccountID", DbType="VarChar(20)")]
		public string ConsoAccountID
		{
			get
			{
				return this._ConsoAccountID;
			}
			set
			{
				if ((this._ConsoAccountID != value))
				{
					this.OnConsoAccountIDChanging(value);
					this.SendPropertyChanging();
					this._ConsoAccountID = value;
					this.SendPropertyChanged("ConsoAccountID");
					this.OnConsoAccountIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ModuleID
		{
			get
			{
				return this._ModuleID;
			}
			set
			{
				if ((this._ModuleID != value))
				{
					this.OnModuleIDChanging(value);
					this.SendPropertyChanging();
					this._ModuleID = value;
					this.SendPropertyChanged("ModuleID");
					this.OnModuleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleOfTranfer", DbType="TinyInt NOT NULL")]
		public byte StyleOfTranfer
		{
			get
			{
				return this._StyleOfTranfer;
			}
			set
			{
				if ((this._StyleOfTranfer != value))
				{
					this.OnStyleOfTranferChanging(value);
					this.SendPropertyChanging();
					this._StyleOfTranfer = value;
					this.SendPropertyChanged("StyleOfTranfer");
					this.OnStyleOfTranferChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountStatus", DbType="TinyInt NOT NULL")]
		public byte AccountStatus
		{
			get
			{
				return this._AccountStatus;
			}
			set
			{
				if ((this._AccountStatus != value))
				{
					this.OnAccountStatusChanging(value);
					this.SendPropertyChanging();
					this._AccountStatus = value;
					this.SendPropertyChanged("AccountStatus");
					this.OnAccountStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountRemark", DbType="VarChar(250)")]
		public string AccountRemark
		{
			get
			{
				return this._AccountRemark;
			}
			set
			{
				if ((this._AccountRemark != value))
				{
					this.OnAccountRemarkChanging(value);
					this.SendPropertyChanging();
					this._AccountRemark = value;
					this.SendPropertyChanged("AccountRemark");
					this.OnAccountRemarkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCode01ID", DbType="VarChar(20)")]
		public string TCode01ID
		{
			get
			{
				return this._TCode01ID;
			}
			set
			{
				if ((this._TCode01ID != value))
				{
					this.OnTCode01IDChanging(value);
					this.SendPropertyChanging();
					this._TCode01ID = value;
					this.SendPropertyChanged("TCode01ID");
					this.OnTCode01IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCode02ID", DbType="VarChar(20)")]
		public string TCode02ID
		{
			get
			{
				return this._TCode02ID;
			}
			set
			{
				if ((this._TCode02ID != value))
				{
					this.OnTCode02IDChanging(value);
					this.SendPropertyChanging();
					this._TCode02ID = value;
					this.SendPropertyChanged("TCode02ID");
					this.OnTCode02IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCode03ID", DbType="VarChar(20)")]
		public string TCode03ID
		{
			get
			{
				return this._TCode03ID;
			}
			set
			{
				if ((this._TCode03ID != value))
				{
					this.OnTCode03IDChanging(value);
					this.SendPropertyChanging();
					this._TCode03ID = value;
					this.SendPropertyChanged("TCode03ID");
					this.OnTCode03IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCode04ID", DbType="VarChar(20)")]
		public string TCode04ID
		{
			get
			{
				return this._TCode04ID;
			}
			set
			{
				if ((this._TCode04ID != value))
				{
					this.OnTCode04IDChanging(value);
					this.SendPropertyChanging();
					this._TCode04ID = value;
					this.SendPropertyChanged("TCode04ID");
					this.OnTCode04IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCode05ID", DbType="VarChar(20)")]
		public string TCode05ID
		{
			get
			{
				return this._TCode05ID;
			}
			set
			{
				if ((this._TCode05ID != value))
				{
					this.OnTCode05IDChanging(value);
					this.SendPropertyChanging();
					this._TCode05ID = value;
					this.SendPropertyChanged("TCode05ID");
					this.OnTCode05IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCode06ID", DbType="VarChar(20)")]
		public string TCode06ID
		{
			get
			{
				return this._TCode06ID;
			}
			set
			{
				if ((this._TCode06ID != value))
				{
					this.OnTCode06IDChanging(value);
					this.SendPropertyChanging();
					this._TCode06ID = value;
					this.SendPropertyChanged("TCode06ID");
					this.OnTCode06IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCode07ID", DbType="VarChar(20)")]
		public string TCode07ID
		{
			get
			{
				return this._TCode07ID;
			}
			set
			{
				if ((this._TCode07ID != value))
				{
					this.OnTCode07IDChanging(value);
					this.SendPropertyChanging();
					this._TCode07ID = value;
					this.SendPropertyChanged("TCode07ID");
					this.OnTCode07IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCode08ID", DbType="VarChar(20)")]
		public string TCode08ID
		{
			get
			{
				return this._TCode08ID;
			}
			set
			{
				if ((this._TCode08ID != value))
				{
					this.OnTCode08IDChanging(value);
					this.SendPropertyChanging();
					this._TCode08ID = value;
					this.SendPropertyChanged("TCode08ID");
					this.OnTCode08IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCode09ID", DbType="VarChar(20)")]
		public string TCode09ID
		{
			get
			{
				return this._TCode09ID;
			}
			set
			{
				if ((this._TCode09ID != value))
				{
					this.OnTCode09IDChanging(value);
					this.SendPropertyChanging();
					this._TCode09ID = value;
					this.SendPropertyChanged("TCode09ID");
					this.OnTCode09IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TCode10ID", DbType="VarChar(20)")]
		public string TCode10ID
		{
			get
			{
				return this._TCode10ID;
			}
			set
			{
				if ((this._TCode10ID != value))
				{
					this.OnTCode10IDChanging(value);
					this.SendPropertyChanging();
					this._TCode10ID = value;
					this.SendPropertyChanged("TCode10ID");
					this.OnTCode10IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMatching", DbType="TinyInt")]
		public System.Nullable<byte> IsMatching
		{
			get
			{
				return this._IsMatching;
			}
			set
			{
				if ((this._IsMatching != value))
				{
					this.OnIsMatchingChanging(value);
					this.SendPropertyChanging();
					this._IsMatching = value;
					this.SendPropertyChanged("IsMatching");
					this.OnIsMatchingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsForex", DbType="TinyInt")]
		public System.Nullable<byte> IsForex
		{
			get
			{
				return this._IsForex;
			}
			set
			{
				if ((this._IsForex != value))
				{
					this.OnIsForexChanging(value);
					this.SendPropertyChanging();
					this._IsForex = value;
					this.SendPropertyChanged("IsForex");
					this.OnIsForexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsStockProvision", DbType="TinyInt")]
		public System.Nullable<byte> IsStockProvision
		{
			get
			{
				return this._IsStockProvision;
			}
			set
			{
				if ((this._IsStockProvision != value))
				{
					this.OnIsStockProvisionChanging(value);
					this.SendPropertyChanging();
					this._IsStockProvision = value;
					this.SendPropertyChanged("IsStockProvision");
					this.OnIsStockProvisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsProgress", DbType="TinyInt")]
		public System.Nullable<byte> IsProgress
		{
			get
			{
				return this._IsProgress;
			}
			set
			{
				if ((this._IsProgress != value))
				{
					this.OnIsProgressChanging(value);
					this.SendPropertyChanging();
					this._IsProgress = value;
					this.SendPropertyChanged("IsProgress");
					this.OnIsProgressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OperatorID", DbType="VarChar(20)")]
		public string OperatorID
		{
			get
			{
				return this._OperatorID;
			}
			set
			{
				if ((this._OperatorID != value))
				{
					this.OnOperatorIDChanging(value);
					this.SendPropertyChanging();
					this._OperatorID = value;
					this.SendPropertyChanged("OperatorID");
					this.OnOperatorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankCode", DbType="VarChar(20)")]
		public string BankCode
		{
			get
			{
				return this._BankCode;
			}
			set
			{
				if ((this._BankCode != value))
				{
					this.OnBankCodeChanging(value);
					this.SendPropertyChanging();
					this._BankCode = value;
					this.SendPropertyChanged("BankCode");
					this.OnBankCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="VarChar(100)")]
		public string BankName
		{
			get
			{
				return this._BankName;
			}
			set
			{
				if ((this._BankName != value))
				{
					this.OnBankNameChanging(value);
					this.SendPropertyChanging();
					this._BankName = value;
					this.SendPropertyChanged("BankName");
					this.OnBankNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchName", DbType="VarChar(250)")]
		public string BranchName
		{
			get
			{
				return this._BranchName;
			}
			set
			{
				if ((this._BranchName != value))
				{
					this.OnBranchNameChanging(value);
					this.SendPropertyChanging();
					this._BranchName = value;
					this.SendPropertyChanged("BranchName");
					this.OnBranchNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAddress", DbType="VarChar(250)")]
		public string BankAddress
		{
			get
			{
				return this._BankAddress;
			}
			set
			{
				if ((this._BankAddress != value))
				{
					this.OnBankAddressChanging(value);
					this.SendPropertyChanging();
					this._BankAddress = value;
					this.SendPropertyChanged("BankAddress");
					this.OnBankAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankPhone", DbType="VarChar(50)")]
		public string BankPhone
		{
			get
			{
				return this._BankPhone;
			}
			set
			{
				if ((this._BankPhone != value))
				{
					this.OnBankPhoneChanging(value);
					this.SendPropertyChanging();
					this._BankPhone = value;
					this.SendPropertyChanged("BankPhone");
					this.OnBankPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankFax", DbType="VarChar(50)")]
		public string BankFax
		{
			get
			{
				return this._BankFax;
			}
			set
			{
				if ((this._BankFax != value))
				{
					this.OnBankFaxChanging(value);
					this.SendPropertyChanging();
					this._BankFax = value;
					this.SendPropertyChanged("BankFax");
					this.OnBankFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAccountNo", DbType="VarChar(50)")]
		public string BankAccountNo
		{
			get
			{
				return this._BankAccountNo;
			}
			set
			{
				if ((this._BankAccountNo != value))
				{
					this.OnBankAccountNoChanging(value);
					this.SendPropertyChanging();
					this._BankAccountNo = value;
					this.SendPropertyChanged("BankAccountNo");
					this.OnBankAccountNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAccountName", DbType="VarChar(250)")]
		public string BankAccountName
		{
			get
			{
				return this._BankAccountName;
			}
			set
			{
				if ((this._BankAccountName != value))
				{
					this.OnBankAccountNameChanging(value);
					this.SendPropertyChanging();
					this._BankAccountName = value;
					this.SendPropertyChanged("BankAccountName");
					this.OnBankAccountNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CurrencyID", DbType="VarChar(20)")]
		public string CurrencyID
		{
			get
			{
				return this._CurrencyID;
			}
			set
			{
				if ((this._CurrencyID != value))
				{
					this.OnCurrencyIDChanging(value);
					this.SendPropertyChanging();
					this._CurrencyID = value;
					this.SendPropertyChanged("CurrencyID");
					this.OnCurrencyIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OpenDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> OpenDate
		{
			get
			{
				return this._OpenDate;
			}
			set
			{
				if ((this._OpenDate != value))
				{
					this.OnOpenDateChanging(value);
					this.SendPropertyChanging();
					this._OpenDate = value;
					this.SendPropertyChanged("OpenDate");
					this.OnOpenDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CloseDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CloseDate
		{
			get
			{
				return this._CloseDate;
			}
			set
			{
				if ((this._CloseDate != value))
				{
					this.OnCloseDateChanging(value);
					this.SendPropertyChanging();
					this._CloseDate = value;
					this.SendPropertyChanged("CloseDate");
					this.OnCloseDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintDetail", DbType="TinyInt NOT NULL")]
		public byte PrintDetail
		{
			get
			{
				return this._PrintDetail;
			}
			set
			{
				if ((this._PrintDetail != value))
				{
					this.OnPrintDetailChanging(value);
					this.SendPropertyChanging();
					this._PrintDetail = value;
					this.SendPropertyChanged("PrintDetail");
					this.OnPrintDetailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UseD90", DbType="TinyInt NOT NULL")]
		public byte UseD90
		{
			get
			{
				return this._UseD90;
			}
			set
			{
				if ((this._UseD90 != value))
				{
					this.OnUseD90Changing(value);
					this.SendPropertyChanging();
					this._UseD90 = value;
					this.SendPropertyChanged("UseD90");
					this.OnUseD90Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName01", DbType="VarChar(250) NOT NULL", CanBeNull=false)]
		public string AccountName01
		{
			get
			{
				return this._AccountName01;
			}
			set
			{
				if ((this._AccountName01 != value))
				{
					this.OnAccountName01Changing(value);
					this.SendPropertyChanging();
					this._AccountName01 = value;
					this.SendPropertyChanged("AccountName01");
					this.OnAccountName01Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintOriginalInBS", DbType="TinyInt NOT NULL")]
		public byte PrintOriginalInBS
		{
			get
			{
				return this._PrintOriginalInBS;
			}
			set
			{
				if ((this._PrintOriginalInBS != value))
				{
					this.OnPrintOriginalInBSChanging(value);
					this.SendPropertyChanging();
					this._PrintOriginalInBS = value;
					this.SendPropertyChanged("PrintOriginalInBS");
					this.OnPrintOriginalInBSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNameU", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string AccountNameU
		{
			get
			{
				return this._AccountNameU;
			}
			set
			{
				if ((this._AccountNameU != value))
				{
					this.OnAccountNameUChanging(value);
					this.SendPropertyChanging();
					this._AccountNameU = value;
					this.SendPropertyChanged("AccountNameU");
					this.OnAccountNameUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountName01U", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string AccountName01U
		{
			get
			{
				return this._AccountName01U;
			}
			set
			{
				if ((this._AccountName01U != value))
				{
					this.OnAccountName01UChanging(value);
					this.SendPropertyChanging();
					this._AccountName01U = value;
					this.SendPropertyChanged("AccountName01U");
					this.OnAccountName01UChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountRemarkU", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string AccountRemarkU
		{
			get
			{
				return this._AccountRemarkU;
			}
			set
			{
				if ((this._AccountRemarkU != value))
				{
					this.OnAccountRemarkUChanging(value);
					this.SendPropertyChanging();
					this._AccountRemarkU = value;
					this.SendPropertyChanged("AccountRemarkU");
					this.OnAccountRemarkUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankNameU", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string BankNameU
		{
			get
			{
				return this._BankNameU;
			}
			set
			{
				if ((this._BankNameU != value))
				{
					this.OnBankNameUChanging(value);
					this.SendPropertyChanging();
					this._BankNameU = value;
					this.SendPropertyChanged("BankNameU");
					this.OnBankNameUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchNameU", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string BranchNameU
		{
			get
			{
				return this._BranchNameU;
			}
			set
			{
				if ((this._BranchNameU != value))
				{
					this.OnBranchNameUChanging(value);
					this.SendPropertyChanging();
					this._BranchNameU = value;
					this.SendPropertyChanged("BranchNameU");
					this.OnBranchNameUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAddressU", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string BankAddressU
		{
			get
			{
				return this._BankAddressU;
			}
			set
			{
				if ((this._BankAddressU != value))
				{
					this.OnBankAddressUChanging(value);
					this.SendPropertyChanging();
					this._BankAddressU = value;
					this.SendPropertyChanged("BankAddressU");
					this.OnBankAddressUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankAccountNameU", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string BankAccountNameU
		{
			get
			{
				return this._BankAccountNameU;
			}
			set
			{
				if ((this._BankAccountNameU != value))
				{
					this.OnBankAccountNameUChanging(value);
					this.SendPropertyChanging();
					this._BankAccountNameU = value;
					this.SendPropertyChanged("BankAccountNameU");
					this.OnBankAccountNameUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IseBanking", DbType="TinyInt NOT NULL")]
		public byte IseBanking
		{
			get
			{
				return this._IseBanking;
			}
			set
			{
				if ((this._IseBanking != value))
				{
					this.OnIseBankingChanging(value);
					this.SendPropertyChanging();
					this._IseBanking = value;
					this.SendPropertyChanged("IseBanking");
					this.OnIseBankingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OfficeCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string OfficeCode
		{
			get
			{
				return this._OfficeCode;
			}
			set
			{
				if ((this._OfficeCode != value))
				{
					this.OnOfficeCodeChanging(value);
					this.SendPropertyChanging();
					this._OfficeCode = value;
					this.SendPropertyChanged("OfficeCode");
					this.OnOfficeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsRevalueExchangeRate", DbType="TinyInt NOT NULL")]
		public byte IsRevalueExchangeRate
		{
			get
			{
				return this._IsRevalueExchangeRate;
			}
			set
			{
				if ((this._IsRevalueExchangeRate != value))
				{
					this.OnIsRevalueExchangeRateChanging(value);
					this.SendPropertyChanging();
					this._IsRevalueExchangeRate = value;
					this.SendPropertyChanged("IsRevalueExchangeRate");
					this.OnIsRevalueExchangeRateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAutoVATTrans", DbType="TinyInt NOT NULL")]
		public byte IsAutoVATTrans
		{
			get
			{
				return this._IsAutoVATTrans;
			}
			set
			{
				if ((this._IsAutoVATTrans != value))
				{
					this.OnIsAutoVATTransChanging(value);
					this.SendPropertyChanging();
					this._IsAutoVATTrans = value;
					this.SendPropertyChanged("IsAutoVATTrans");
					this.OnIsAutoVATTransChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DebitAccVATTrans", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DebitAccVATTrans
		{
			get
			{
				return this._DebitAccVATTrans;
			}
			set
			{
				if ((this._DebitAccVATTrans != value))
				{
					this.OnDebitAccVATTransChanging(value);
					this.SendPropertyChanging();
					this._DebitAccVATTrans = value;
					this.SendPropertyChanged("DebitAccVATTrans");
					this.OnDebitAccVATTransChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreditAccVATTrans", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CreditAccVATTrans
		{
			get
			{
				return this._CreditAccVATTrans;
			}
			set
			{
				if ((this._CreditAccVATTrans != value))
				{
					this.OnCreditAccVATTransChanging(value);
					this.SendPropertyChanging();
					this._CreditAccVATTrans = value;
					this.SendPropertyChanged("CreditAccVATTrans");
					this.OnCreditAccVATTransChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsGroupCorAccount", DbType="TinyInt NOT NULL")]
		public byte IsGroupCorAccount
		{
			get
			{
				return this._IsGroupCorAccount;
			}
			set
			{
				if ((this._IsGroupCorAccount != value))
				{
					this.OnIsGroupCorAccountChanging(value);
					this.SendPropertyChanging();
					this._IsGroupCorAccount = value;
					this.SendPropertyChanged("IsGroupCorAccount");
					this.OnIsGroupCorAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GainFXAccount", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string GainFXAccount
		{
			get
			{
				return this._GainFXAccount;
			}
			set
			{
				if ((this._GainFXAccount != value))
				{
					this.OnGainFXAccountChanging(value);
					this.SendPropertyChanging();
					this._GainFXAccount = value;
					this.SendPropertyChanged("GainFXAccount");
					this.OnGainFXAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LossFXAccount", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string LossFXAccount
		{
			get
			{
				return this._LossFXAccount;
			}
			set
			{
				if ((this._LossFXAccount != value))
				{
					this.OnLossFXAccountChanging(value);
					this.SendPropertyChanging();
					this._LossFXAccount = value;
					this.SendPropertyChanged("LossFXAccount");
					this.OnLossFXAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StrDivisionID", DbType="VarChar(8000) NOT NULL", CanBeNull=false)]
		public string StrDivisionID
		{
			get
			{
				return this._StrDivisionID;
			}
			set
			{
				if ((this._StrDivisionID != value))
				{
					this.OnStrDivisionIDChanging(value);
					this.SendPropertyChanging();
					this._StrDivisionID = value;
					this.SendPropertyChanged("StrDivisionID");
					this.OnStrDivisionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StrRoleID", DbType="VarChar(8000) NOT NULL", CanBeNull=false)]
		public string StrRoleID
		{
			get
			{
				return this._StrRoleID;
			}
			set
			{
				if ((this._StrRoleID != value))
				{
					this.OnStrRoleIDChanging(value);
					this.SendPropertyChanging();
					this._StrRoleID = value;
					this.SendPropertyChanged("StrRoleID");
					this.OnStrRoleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExcessAccount", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ExcessAccount
		{
			get
			{
				return this._ExcessAccount;
			}
			set
			{
				if ((this._ExcessAccount != value))
				{
					this.OnExcessAccountChanging(value);
					this.SendPropertyChanging();
					this._ExcessAccount = value;
					this.SendPropertyChanged("ExcessAccount");
					this.OnExcessAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DeficiencyAccount", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string DeficiencyAccount
		{
			get
			{
				return this._DeficiencyAccount;
			}
			set
			{
				if ((this._DeficiencyAccount != value))
				{
					this.OnDeficiencyAccountChanging(value);
					this.SendPropertyChanging();
					this._DeficiencyAccount = value;
					this.SendPropertyChanged("DeficiencyAccount");
					this.OnDeficiencyAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentGainFXAccount", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PaymentGainFXAccount
		{
			get
			{
				return this._PaymentGainFXAccount;
			}
			set
			{
				if ((this._PaymentGainFXAccount != value))
				{
					this.OnPaymentGainFXAccountChanging(value);
					this.SendPropertyChanging();
					this._PaymentGainFXAccount = value;
					this.SendPropertyChanged("PaymentGainFXAccount");
					this.OnPaymentGainFXAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentLossFXAccount", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PaymentLossFXAccount
		{
			get
			{
				return this._PaymentLossFXAccount;
			}
			set
			{
				if ((this._PaymentLossFXAccount != value))
				{
					this.OnPaymentLossFXAccountChanging(value);
					this.SendPropertyChanging();
					this._PaymentLossFXAccount = value;
					this.SendPropertyChanged("PaymentLossFXAccount");
					this.OnPaymentLossFXAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMatchingD03D04", DbType="TinyInt NOT NULL")]
		public byte IsMatchingD03D04
		{
			get
			{
				return this._IsMatchingD03D04;
			}
			set
			{
				if ((this._IsMatchingD03D04 != value))
				{
					this.OnIsMatchingD03D04Changing(value);
					this.SendPropertyChanging();
					this._IsMatchingD03D04 = value;
					this.SendPropertyChanged("IsMatchingD03D04");
					this.OnIsMatchingD03D04Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsMappingAnalysis", DbType="TinyInt NOT NULL")]
		public byte IsMappingAnalysis
		{
			get
			{
				return this._IsMappingAnalysis;
			}
			set
			{
				if ((this._IsMappingAnalysis != value))
				{
					this.OnIsMappingAnalysisChanging(value);
					this.SendPropertyChanging();
					this._IsMappingAnalysis = value;
					this.SendPropertyChanged("IsMappingAnalysis");
					this.OnIsMappingAnalysisChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecVoucherTypeID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string RecVoucherTypeID
		{
			get
			{
				return this._RecVoucherTypeID;
			}
			set
			{
				if ((this._RecVoucherTypeID != value))
				{
					this.OnRecVoucherTypeIDChanging(value);
					this.SendPropertyChanging();
					this._RecVoucherTypeID = value;
					this.SendPropertyChanged("RecVoucherTypeID");
					this.OnRecVoucherTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayVoucherTypeID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PayVoucherTypeID
		{
			get
			{
				return this._PayVoucherTypeID;
			}
			set
			{
				if ((this._PayVoucherTypeID != value))
				{
					this.OnPayVoucherTypeIDChanging(value);
					this.SendPropertyChanging();
					this._PayVoucherTypeID = value;
					this.SendPropertyChanged("PayVoucherTypeID");
					this.OnPayVoucherTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountDAG", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string AccountDAG
		{
			get
			{
				return this._AccountDAG;
			}
			set
			{
				if ((this._AccountDAG != value))
				{
					this.OnAccountDAGChanging(value);
					this.SendPropertyChanging();
					this._AccountDAG = value;
					this.SendPropertyChanged("AccountDAG");
					this.OnAccountDAGChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
